
language: node_js
node_js:
  - 4
  - stable

sudo: false

before_install:
  - export CHROME_BIN=chromium-browser  # Karma CI
  - export DISPLAY=:99.0

before_script:
  - sh -e /etc/init.d/xvfb start
  # - nohup bash -c webdriver-manager start 2>&1 &  # Protractor CI
  - sleep 1  # give server time to start
script:
 - npm run build.prod
 - bash ./.travis-deploy.sh

after_failure:
  - cat /home/travis/build/mgechev/angular2-seed/npm-debug.log

branches:
  only: master


cache:
directories: node_modules
